[package]
name = "pikagent"
version = "0.1.0"
edition = "2021"
authors = ["atopx <3940422@qq.com>"]
repository = "https://github.com/atopx/pikagent.git"
description = "agent pikafish"
license = "MIT"
keywords = ["pikafish", "xiangqi", "chinese chess"]

[dependencies]
